namubufferi:
        build: ./
        environment:
                DEBUG: "true"
                NAMUBUFFERI_ALLOWEDHOSTS: localhost
                NAMUBUFFERI_ADMINUSER: admin
                NAMUBUFFERI_ADMINPASS: password
                NAMUBUFFERI_GUNICORN_WORKERS: 1
                NAMUBUFFERI_DB: postgres://postgres:postgres@postgres/namubufferi-local-test
                NAMUBUFFERI_SECRETKEY: 'wfofh1#8444fufhIUFOHFEHUFW3D73D7344/((#(#HFFH'
                NAMUBUFFERI_STATIC_URL: /static/
                NAMUBUFFERI_ADMIN_EMAILS: 'something@example.com'
        links:
                - postgres:postgres
        ports:
                - 8080:8080
        volumes:
                - ./namubufferiapp:/namubufferi/namubufferiapp

postgres:
        image: postgres:alpine
        environment:
                POSTGRES_DB: namubufferi-local-test
