namubufferi:
        build: ../
        dockerfile: docker-files/namubufferi/Dockerfile
        volumes:
                - /static
        links:
                - postgres:postgres
                - ldap:ldap
                - smtp:smtp

smtp:
        image: namshi/smtp

ldap:
        restart: always
        build: ./slapd/

postgres:
        image: postgres:alpine

nginx:
        build: ./nginx/
        ports:
                - "80:80"
        volumes_from:
                - namubufferi
        links:
                - namubufferi:namubufferi
